---
# OOB Management network default gateway
mgmt_gateway: 192.168.0.1
# If ATD is running cEOS, management interface is Management0
# If ATD is running vEOS, management interface is Management1
mgmt_interface: Management0
mgmt_interface_vrf: default

dns_domain: atd.lab

local_users:

  - name: admin
    privilege: 15
    role: network-admin
    sha512_password: $6$1oyLy5zCFpoXLPEc$MptVAiX.kLOXdJQieDVMz5lfPSqyZpYROs3k/qpCLz0nq4lcmp0FaQI1uvRuVoE6Bmb2SOa//Lnz2pv6l7hHf/

  - name: arista
    privilege: 15
    role: network-admin
    sha512_password: $6$1oyLy5zCFpoXLPEc$MptVAiX.kLOXdJQieDVMz5lfPSqyZpYROs3k/qpCLz0nq4lcmp0FaQI1uvRuVoE6Bmb2SOa//Lnz2pv6l7hHf/

# cvp_ingestauth_key: <str>
cvp_instance_ips:
  - 192.168.0.5
# cvp_token_file: token,/tmp/token
terminattr_disable_aaa: True
terminattr_ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
terminattr_ingestgrpcurl_port: 9910
terminattr_smashexcludes: ale,flexCounter,hardware,kni,pulse,strata

source_interfaces:

  radius:
    mgmt_interface: True

radius_server:
  hosts:
    - host: 192.168.0.1
      key: 0207165218120E

ntp:
  servers:
    - name: 192.168.0.1
      iburst: True
      local_interface: Management0

aaa_authentication:
  login:
    default: group atds local
aaa_authorization:
  exec:
    default: group atds local
  commands:
    all_default: local
aaa_server_groups:
  - name: atds
    type: radius
    servers:
      - server: 192.168.0.1
