---
# tasks file for atd-provisioner
# tasks file for eos-config-deploy-cvp - state=present
- name: 'Collecting facts from CVP {{inventory_hostname}}.'
  tags: [always]
  arista.cvp.cv_facts:
  register: CVP_FACTS

- name: "Building Containers topology on {{inventory_hostname}}"
  tags: [provision, apply]
  arista.cvp.cv_container:
    topology: '{{CVP_CONTAINERS_INIT}}'
    cvp_facts: '{{CVP_FACTS.ansible_facts}}'
    mode: override

- name: 'Refreshing facts from CVP {{inventory_hostname}}.'
  tags: [always]
  arista.cvp.cv_facts:
  register: CVP_FACTS

- name: "Configure devices on {{inventory_hostname}}"
  tags: [provision, apply]
  arista.cvp.cv_device:
    devices: "{{CVP_DEVICES_INIT}}"
    cvp_facts: '{{CVP_FACTS.ansible_facts}}'
    state: present
  register: CVP_DEVICES_RESULTS

- name: "Execute pending tasks on {{inventory_hostname}}"
  tags: [apply]
  arista.cvp.cv_task:
    tasks: "{{ CVP_DEVICES_RESULTS.data.tasks }}"
    wait: 720
  when:
    - execute_tasks|bool

- name: 'Collecting facts from CVP {{inventory_hostname}}.'
  tags: [always]
  arista.cvp.cv_facts:
  register: CVP_FACTS

- name: "Refresh Containers topology on {{inventory_hostname}}"
  tags: [provision, apply]
  arista.cvp.cv_container:
    topology: '{{CVP_CONTAINERS_INIT}}'
    cvp_facts: '{{CVP_FACTS.ansible_facts}}'
    mode: override
