## Ansible Generated ##

### Host2 ###


### Leaf Info ###
l2leaf_node_group: DC1_L2LEAF2
switch_platform: vEOS-LAB
leaf_id: 7
switch_mgmt_ip: 192.168.0.17/24
leaf_filter_tenants: ['Tenant_A']
leaf_filter_tags: ['opzone', 'web', 'app']
leaf_allowed_vrfs: ['Tenant_A_APP_Zone', 'Tenant_A_OP_Zone', 'Tenant_A_WEB_Zone']
leaf_allowed_svis: [130, 131, 110, 111, 112, 120, 121]
leaf_allowed_vlans: [130, 131, 110, 111, 112, 120, 121]
leaf_mlag: False

service_routing_protocols_model: multi-agent
ip_routing: true

### Hardware Counter
hardware_counters:

### Daemon TerminAttr
daemon_terminattr:
  ingestgrpcurl:
    ips:
      - 192.168.0.5
    port: 9910
  ingestauth_key: atd-lab
  ingestvrf: default
  smashexcludes: "ale,flexCounter,hardware,kni,pulse,strata"
  ingestexclude: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"

vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199

### Event Monitor ###
event_monitor:

### Event Handler ###
event_handlers:

### Load Interval ###
load_interval:

### Queue Monitor Lenght ###
queue_monitor_length:

### Logging ###
logging:

### Name Servers ###
name_server:
  source:
    vrf: default
  nodes:
    - 192.168.0.1
    - 8.8.8.8

### NTP Servers ###
ntp_server:
  local_interface:
    vrf: default
    interface: Management1
  nodes:
    - 192.168.0.1
    - 0.fr.pool.ntp.org
    - 1.fr.pool.ntp.org

### Redundancy ###
redundancy:

### Spanning-tree ###
spanning_tree:
  mode: mstp
  priority: 16384


### AAA authorization ###
aaa_authorization:

### local users ###
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$4Hh3HEdiGgzbXYGR$WM3lNvPcKmjNfoxeA5fpqoSXpNLkM7D84xMYUME19nqna.4MhvoTQ0SDo3eBSncR8RftDsmxmLX0gCKMtfBhp1
  arista:
    privilege: 15
    role: network-admin
    sha512_password: $6$O9x7MCScI/Gbkczt$TFyd73bh9QubmKyZqteauUX7C5BMvUK7EI3jnoR5rqN1p5X9GBTHIxa.yZaN4.UG39nYODcCGcuP9Gn1siKe00

### Clock Timezone ###
clock:

### VLANs ###
vlans:

## Tenant_A ##
  130:
    tenant: Tenant_A
    name: Tenant_A_APP_Zone_1
  131:
    tenant: Tenant_A
    name: Tenant_A_APP_Zone_2
  110:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_1
  111:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_2
  112:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_3
  120:
    tenant: Tenant_A
    name: Tenant_A_WEB_Zone_1
  121:
    tenant: Tenant_A
    name: Tenant_A_WEBZone_2

### VRFs ###
vrfs:
  default:
    ip_routing: False
### Port-Channel Interfaces ###
port_channel_interfaces:
  Port-Channel1:
    description: Leaf3_Po4
    vlans: 110-112,120-121,130-131
    mode: trunk
    mlag: 1

### Ethernet Interfaces ###
ethernet_interfaces:
## L3 LEAF link ##
  Ethernet1:
    peer: Leaf3
    peer_interface: Ethernet4
    peer_type: l3leaf
    description: Leaf3_Ethernet4
    channel_group:
      id: 1
      mode: active
## L3 LEAF link ##
  Ethernet3:
    peer: Leaf3
    peer_interface: Ethernet5
    peer_type: l3leaf
    description: Leaf3_Ethernet5
    channel_group:
      id: 1
      mode: active
## L3 LEAF link ##
  Ethernet2:
    peer: Leaf4
    peer_interface: Ethernet4
    peer_type: l3leaf
    description: Leaf4_Ethernet4
    channel_group:
      id: 1
      mode: active
## L3 LEAF link ##
  Ethernet4:
    peer: Leaf4
    peer_interface: Ethernet5
    peer_type: l3leaf
    description: Leaf4_Ethernet5
    channel_group:
      id: 1
      mode: active

### Management Interfaces ###
management_interfaces:
  Management1:
    description: oob_management
    vrf: default
    ip_address: 192.168.0.17/24
    gateway: 192.168.0.1

### VLAN Interfaces ###
vlan_interfaces:

### TCAM Profiles ###
tcam_profile:

### MAC address table ###
mac_address_table:

### static routes ###
static_routes:
  - vrf: default
    destination_address_prefix: 0.0.0.0/0
    gateway: 192.168.0.1


### Queue Monitor Streaming ###
queue_monitor_streaming:

### Management API http ###
management_api_http:
  enable_https: True
  enable_vrfs:
    default:
