---
all:
  children:
    CVP:
      hosts:
        # cv_ztp:
        #   ansible_host: 192.168.0.5
        #   ansible_user: root
        #   ansible_password: ansible
        cv_server:
          ansible_httpapi_host: 192.168.0.5
          ansible_host: 192.168.0.5
          ansible_user: arista
          ansible_password: arista
          ansible_connection: httpapi
          ansible_httpapi_use_ssl: true
          ansible_httpapi_validate_certs: false
          ansible_network_os: eos
          ansible_httpapi_port: 443
          # Configuration to get Virtual Env information
          ansible_python_interpreter: $(which python3)
    # DC1_Fabric - EVPN Fabric running in home lab
    DC1:
      children:
        DC1_FABRIC:
          children:
            DC1_SPINES:
              hosts:
                Spine1:
                  ansible_host: 192.168.0.10
                Spine2:
                  ansible_host: 192.168.0.11
            DC1_L3LEAFS:
              children:
                DC1_LEAF1:
                  hosts:
                    Leaf1:
                      ansible_host: 192.168.0.12
                    Leaf2:
                      ansible_host: 192.168.0.13
                DC1_LEAF2:
                  hosts:
                    Leaf3:
                      ansible_host: 192.168.0.14
                    Leaf4:
                      ansible_host: 192.168.0.15
            DC1_L2LEAFS:
              children:
                DC1_L2LEAF1:
                  hosts:
                    Host1:
                      ansible_host: 192.168.0.16
                DC1_L2LEAF2:
                  hosts:
                   Host2:
                      ansible_host: 192.168.0.17
          vars:
            ansible_connection: httpapi
            ansible_network_os: eos
            ansible_user: arista
            # should use vault for passwords
            ansible_ssh_pass: arista
            ansible_become: true
            ansible_become_method: enable
            ansible_httpapi_use_ssl: true
            ansible_httpapi_validate_certs: false
        DC1_TENANTS_NETWORKS:
          children:
            DC1_L3LEAFS:
            DC1_L2LEAFS:
        DC1_SERVERS:
          children:
            DC1_L3LEAFS:
            DC1_L2LEAFS:
