---
- name: Configuration deployment with CV
  hosts: ATD_FABRIC
  connection: local
  gather_facts: false
  collections:
    - arista.avd
  tasks:
    - name: Provision CVP with AVD configuration
      import_role:
        name: cv_deploy
      vars:
        cv_server: aap-1-6495533d-eos.topo.testdrive.arista.com
        cv_token: "{{ lab_token }}"
        cv_run_change_control: true
